project:
  type: "website"
  title: "Fall 2025 Courses"
  output-dir: _output
  render:
    - "./index.qmd"
    - "2026_intro/*"

website:
  title: "Spring 2026"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card:
    creator: "@<twitter-handle>"
    site: "\\@<twitter-handle>"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: ./index.qmd
        text: "ğŸ  Lecture Notes and Slides"
      - section: "ğŸ—“ï¸ Introduction to Philosophy"
        contents:
         - href: 2026_intro/weeks/week02/page.qmd
           text: Week 01
           contents:
             - href: 2026_intro/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_intro/weeks/week02/summary.qmd
            #    text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week03/page.qmd
           text: Week 02
           contents:
             - href: 2026_intro/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_intro/weeks/week03/summary.qmd
            #    text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week04/page.qmd
           text: Week 03
           contents:
             - href: 2026_intro/weeks/week04/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_intro/weeks/week04/summary.qmd
            #    text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week05/page.qmd
           text: Week 04
           contents:
             - href: 2026_intro/weeks/week05/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week05/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week06/page.qmd
           text: Week 05
           contents:
             - href: 2026_intro/weeks/week06/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week06/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week07/page.qmd
           text: Week 07
           contents:
             - href: 2026_intro/weeks/week07/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week07/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week08/page.qmd
           text: Week 08
           contents:
             - href: 2026_intro/weeks/week08/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week08/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week09/page.qmd
           text: Week 09
           contents:
             - href: 2026_intro/weeks/week09/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week09/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix href: 2026_intro/weeks/week08/page.qmd
         - href: 2026_intro/weeks/week02/page.qmd
           text: Week 10
           contents:
             - href: 2026_intro/weeks/week02/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_intro/weeks/week02/summary.qmd
            #    text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week03/page.qmd
           text: Week 11
           contents:
             - href: 2026_intro/weeks/week03/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_intro/weeks/week03/summary.qmd
            #    text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week04/page.qmd
           text: Week 12
           contents:
             - href: 2026_intro/weeks/week04/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
            #  - href: 2026_intro/weeks/week04/summary.qmd
            #    text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week05/page.qmd
           text: Week 13
           contents:
             - href: 2026_intro/weeks/week05/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week05/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week06/page.qmd
           text: Week 14
           contents:
             - href: 2026_intro/weeks/week06/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week06/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week07/page.qmd
           text: Week 15
           contents:
             - href: 2026_intro/weeks/week07/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week07/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
         - href: 2026_intro/weeks/week08/page.qmd
           text: Week 16
           contents:
             - href: 2026_intro/weeks/week08/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
             - href: 2026_intro/weeks/week08/summary.qmd
               text: ğŸ’» Notes and Summary
            #  - href: 2023/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix

  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2025, Montaque Reynolds"



bibliography: references/Un-Duplicates.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr. [Reynolds](#)
    author-meta: Dr. Monty Reynolds
    date-format: "MMM DD, YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light:
        - journal
        - css/custom.scss # I use this just to change the default colour
    css:
      - css/custom_style.css
      - css/syllabus.css
    toc: true

margin-header: |
 ![](/figures/logos/logo-x2.png)
